version: '3.8'

services:
  telegram-message-bot:
    image: hav93/telegram-message-bot:test
    container_name: telegram-message-bot
    restart: always

    ports:
      - "9393:9393"

    environment:
      - TZ=Asia/Shanghai
      
      # === Telegram API配置 ===
      # 请在 .env 文件中设置这些值，或通过环境变量传递
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - PHONE_NUMBER=${PHONE_NUMBER}
      - ADMIN_USER_IDS=${ADMIN_USER_IDS}
      
      # === 代理配置（可选）===
      # 外网环境可不设置代理
      - ENABLE_PROXY=${ENABLE_PROXY:-false}
      - PROXY_TYPE=${PROXY_TYPE:-http}
      - PROXY_HOST=${PROXY_HOST:-127.0.0.1}
      - PROXY_PORT=${PROXY_PORT:-1080}
      - PROXY_USERNAME=${PROXY_USERNAME:-}
      - PROXY_PASSWORD=${PROXY_PASSWORD:-}
      
      # === 应用配置 ===
      - DATABASE_URL=sqlite:///data/bot.db
      - WEB_HOST=0.0.0.0
      - WEB_PORT=9393
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      
      # === 日志管理配置 ===
      - ENABLE_LOG_CLEANUP=${ENABLE_LOG_CLEANUP:-true}
      - LOG_RETENTION_DAYS=${LOG_RETENTION_DAYS:-30}
      - LOG_CLEANUP_TIME=${LOG_CLEANUP_TIME:-02:00}
      - MAX_LOG_SIZE=${MAX_LOG_SIZE:-100}
      
      # === 权限配置 ===
      - PUID=1000
      - PGID=1000
      
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./sessions:/app/sessions
      - ./temp:/app/temp
      
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  telegram-net:
    driver: bridge