name: Simple Docker Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check Docker Hub credentials
      run: |
        echo "🔍 检查Docker Hub凭据..."
        echo "DOCKER_USERNAME length: ${#DOCKER_USERNAME}"
        echo "DOCKER_PASSWORD length: ${#DOCKER_PASSWORD}"
        if [ -z "$DOCKER_USERNAME" ]; then
          echo "❌ DOCKER_USERNAME secret not set"
          echo "请检查GitHub仓库Settings -> Secrets and variables -> Actions"
          echo "确保添加了名为 'DOCKER_USERNAME' 的secret"
          exit 1
        else
          echo "✅ Docker Hub credentials found"
          echo "Username: ${DOCKER_USERNAME:0:3}***"
        fi
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          hav93/telegram-message-bot:latest
          hav93/telegram-message-bot:v3.6
        platforms: linux/amd64
